name: beater_buddy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  audio_video_progress_bar: ^2.0.3
  just_audio_background: ^0.0.1-beta.16
  just_audio: ^0.10.1
  rxdart: ^0.28.0 
  flutter_tts: ^4.2.2
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tracks.json
    - assets/images/
    - assets/images/albumart/